#!/bin/bash
# iZsh 智能命令翻译演示

echo "════════════════════════════════════════"
echo "  🧠 iZsh 智能命令翻译演示"
echo "════════════════════════════════════════"
echo ""
echo "此演示将展示 iZsh 的智能命令翻译功能："
echo "  ✅ 自然语言 → Shell 命令"
echo "  ✅ 拼写错误自动纠正"
echo "  ✅ 用户确认后执行"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 设置环境变量
export DYLD_LIBRARY_PATH=/Users/zhangzhen/anaconda3/lib

echo "📋 测试场景："
echo ""
echo "场景 1: 自然语言 - '列目录'"
echo "   预期: 翻译为 'ls' 命令"
echo ""
echo "场景 2: 拼写错误 - 'mkdri test'"
echo "   预期: 纠正为 'mkdir test'"
echo ""
echo "场景 3: 中文描述 - '查看文件内容 ~/.izshrc'"
echo "   预期: 翻译为 'cat ~/.izshrc'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 使用方法："
echo ""
echo "1. 启动 iZsh:"
echo "   ./start_izsh.sh"
echo ""
echo "2. 输入自然语言或错误命令:"
echo "   列目录"
echo "   mkdri test"
echo "   查看文件 test.txt"
echo "   删除文件 old.log"
echo ""
echo "3. AI 会自动翻译并询问是否执行"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 现在启动 iZsh 进行实际测试..."
echo ""
echo "提示：在 iZsh 中直接输入以下内容体验："
echo "  - 列目录"
echo "  - 创建目录 testdir"
echo "  - 查看当前路径"
echo "  - 显示磁盘使用情况"
echo ""
echo "按 Ctrl+D 或输入 'exit' 退出 iZsh"
echo ""
echo "════════════════════════════════════════"
echo ""

# 启动 iZsh
~/.local/bin/izsh
