#!/bin/bash
# iZsh 欢迎界面预览

echo ""
echo "            ═══════════════════════════════════"
echo ""
echo "                 ██╗███████╗███████╗██╗  ██╗"
echo "                 ██║╚══███╔╝██╔════╝██║  ██║"
echo "                 ██║  ███╔╝ ███████╗███████║"
echo "                 ██║ ███╔╝  ╚════██║██╔══██║"
echo "                 ██║███████╗███████║██║  ██║"
echo "                 ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝"
echo ""
echo "                   智能终端 - AI 驱动的 Shell"
echo ""
echo "            ═══════════════════════════════════"
echo ""
echo "✨ iZsh AI 模块已加载"
echo "   干预级别: 建议"
echo "   API: https://q.quuvv.cn/v1"
echo "   模型: claude-3-5-haiku-20241022"
echo "   智能翻译: 已启用 (输入自然语言会自动翻译)"
echo "✨ 欢迎使用 iZsh - 智能终端!"
echo "   版本: 1.0.0-izsh"
echo "   AI 功能: 已启用"
echo "   AI 自动确认: 已启用 (3秒超时)"
echo "   日志系统: 已启用 (izsh-logs查看)"
echo ""
